### ISSUE TITLE
where is the RLIP_caption_coco.py?

### ISSUE THREAD

**Issue by ZHUXUHAN** [JacobYuan7/RLIPv2#1]
Where is your script for generating pseudo-labels?

**Comment by JacobYuan7** [comment]
Apologies for forgetting to upload the code for BLIP. I am uploading it right now.

**Comment by JacobYuan7** [comment]
I update the readme with a code link. @ZHUXUHAN

**Comment by ZHUXUHAN** [comment]
> I've updated the readme with a code link. @ZHUXUHAN

ok thanks for your answer
