### ISSUE TITLE
Download link for the generated captions jumps error

### ISSUE THREAD

**Issue by kongzihan** [JacobYuan7/RLIPv2#14]
It appears that the download link for the generated captions has mistakenly jumped to the download page for Zero-shot (HICO) checkpoints. 

> ## Relational pseudo-labelling
> - Step 3: run `scripts/verb_tagger/test_Tagger_resnet.sh` script (which runs `generate_relations_using_verb_tagger.py`) to assign relation texts to region pairs via R-Tagger. The parameters and generated captions can be downloaded from [this link](https://1drv.ms/f/s!Areeng9Fzbjiw1Zs3bHxykLj-GlV?e=W03Jai).

Could you kindly check this for me and rectify the issue?

**Comment by JacobYuan7** [comment]
@kongzihan 
Hi, sorry about the mistake. I've updated the link. Many thanks for the reminder.

**Comment by JacobYuan7** [comment]
Closed as completed. Feel free to re-open it if it fails.
