### ISSUE TITLE
 The OneDrive link for the Downstream Task "Fully fine-tuning on V-COCO" is no longer active.

### ISSUE THREAD

**Issue by Kratos-Wen** [JacobYuan7/RLIPv2#15]
Hi Jacob,thank you for your work! I am trying to download your training weights, but there is no response when I click on the download button in OneDrive link for the Downstream Task "Fully fine-tuning on V-COCO", and using the URL to download also does not work. Could you please update the link for the download file?

**Comment by JacobYuan7** [comment]
@Kratos-Wen 
I tried this link myself and found it could work effectively. Could you post an image to share the error reported? Or could you try other devices to get access to this link?

**Comment by Kratos-Wen** [comment]
@JacobYuan7 
Thank you for your prompt response. I have tried five different network environments, three different devices, and two MS accounts, all of which received the same 503 error when attempting to obtain the download URL. I suspect it is an issue on the server side, possibly due to excessive downloads. I am unable to get any response on my local port (please refer to the attached screenshot from DevTools).
<img width="1280" alt="Fullyfinetuning_HICODET" src="https://github.com/JacobYuan7/RLIPv2/assets/103342237/28a71741-8f0b-49d9-97af-3a976396e726">
<img width="1280" alt="Fullyfinetuning_VCOCO" src="https://github.com/JacobYuan7/RLIPv2/assets/103342237/a84b5c62-b9d5-4078-9ab4-e9687df928cc">

**Comment by JacobYuan7** [comment]
@Kratos-Wen 
Hi, I updated this link. Can you try the new link? Btw, are other links not working as well at your end?
