### ISSUE TITLE
question about Visual Genome dataset

### ISSUE THREAD

**Issue by ztt0821** [JacobYuan7/RLIPv2#16]
Hi, i want to download the Visual Genome dataset, but i can't open the three links of the Visual Genome in readme. I can open this linkhttps://homes.cs.washington.edu/~ranjay/visualgenome/api.html. May I ask which version you used?
Thank you very much.

**Comment by JacobYuan7** [comment]
@ztt0821 
It is weird that these links are not working. I am trying to figure out why.
Btw, I used the newest version of the dataset.

**Comment by ztt0821** [comment]
Hi, thank you for help. Another question is the annotation file of this dataset. I found that you generate the file by yourself in the readme. Could you share the annotation file?

**Comment by JacobYuan7** [comment]
@ztt0821 I updated the link in readme.
