### ISSUE TITLE
Unable to reproduce results for VCOCO with backbone SwinT

### ISSUE THREAD

**Issue by Kratos-Wen** [JacobYuan7/RLIPv2#18]
Hello,
I used the "scripts/RLIP_ParSeDA/fine_tune_RLIP_ParSeDA_v2_vcoco_swinT.sh" script to fine-tune the "RLIP PDA v2 SwinT VGCOO365 BLIP Nu10 thr20 RQL LSE RPL bs64 20e checkpoint0019.pth" model. Apart from reducing the batch size to 2 and setting it up for single-node multi-GPU training, I did not make any other modifications. After 20 epochs, the results I obtained are as shown in the attached image, which significantly differ from the results presented on the homepage. Could you please advise what parameter might be causing this discrepancy?

Thanks in advance!

![image](https://github.com/user-attachments/assets/b4286ade-1428-405f-821b-e95def238ae7)

**Comment by Kratos-Wen** [comment]
PS: Also, I have encountered issues with all fine-tuning models on the HICO-DET and VCOCO datasets using SwinT and SwinL backbones. The results I obtained are about 3~4% lower than those presented in the paper. Additionally, I often experience overfitting, with final results falling in the range below 1. Is this behavior normal?

**Comment by JacobYuan7** [comment]
@Kratos-Wen 
3~4% lower is not normal.
Please refer to the evaluation instructions https://github.com/JacobYuan7/RLIPv2?tab=readme-ov-file#evaluation
The performance reported during training is not the final result. This is done by all previous methods.

Btw, batch size will influence the performance, but I do not think it will have such a significant influence. The evaluation might be the core reason for your low performance.

**Comment by JacobYuan7** [comment]
@Kratos-Wen  I am closing it for now. Feel free to raise follow-up questions.
