### ISSUE TITLE
: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by YuxiaoWang-AI** [JacobYuan7/RLIPv2#19]
hello, the program encountered an issue with gradients when i run "fine_tune_RLIP_ParSeDA_v2_hico_swinL.sh". Error information are as follows:
Traceback (most recent call last):
  File "main.py", line 815, in <module>
    main(args)
  File "main.py", line 722, in main
    args.clip_max_norm, args = args)
  File "/home/zhangyiwen/program/hico/hico3/hico-det/RLIPV2/RLIPv2/engine.py", line 170, in train_one_epoch
    losses.backward()
  File "/var/conda/envs/rlip2/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/var/conda/envs/rlip2/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [198, 5]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Do you know how to solve this problem? We look forward to your reply.

**Comment by JacobYuan7** [comment]
@YuxiaoWang-AI 
Hi, I've never encountered this problem before. I think many people have run this code successfully. Perhaps you can follow the instructions in the reported error info to identify the source of this bug.

**Comment by YuxiaoWang-AI** [comment]
Hello, I reinstalled conda env and now the program is running normally. Additionally, I would like to confirm one thing, is the pre-trained backbone not pre-trained with HICO Det and V-COCO? For example, the following models:
<img width="839" alt="image" src="https://github.com/user-attachments/assets/d01863e0-b2f1-4b8d-b9bd-e895c32a8f55">

**Comment by JacobYuan7** [comment]
@YuxiaoWang-AI  
No, as indicated by the `Pre-training Datasets`, they are not pre-trained on HICO Det and V-COCO. They are downstream datasets.

**Comment by YuxiaoWang-AI** [comment]
ok, thank you very much.
