### ISSUE TITLE
Problem about the pretrained model

### ISSUE THREAD

**Issue by ChelsieLei** [JacobYuan7/RLIPv2#3]
Hi, 
Thanks for your nice work! When I ran the code, I came across the following error.

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data-nas/peizhi/params/resnet50-19c8e357.pth'

Also, I found that many models are under the folder '/mnt/data-nas/peizhi/', but I don't know where to get those models. I also don't find it in the environment configs. 
I would appreciate any reply you can give me. Thank you!

**Comment by JacobYuan7** [comment]
@ChelsieLei 
For the "resnet50-19c8e357.pth", it's simply the default torchvision pre-training for ResNet-50. I preload it to prevent constant re-downloads in fresh environments. To enable automatic downloading, you can make a slight code modification.

Original:
```python
backbone = getattr(torchvision.models, name)(
                    replace_stride_with_dilation=[False, False, dilation],
                    pretrained=False, norm_layer=FrozenBatchNorm2d)
default_sup_pretrain = torch.load('/mnt/data-nas/peizhi/params/resnet50-19c8e357.pth', map_location='cpu')
backbone.load_state_dict(default_sup_pretrain, strict = True)
```
New:
```python
backbone = getattr(torchvision.models, "resnet50")(
    replace_stride_with_dilation=[False, False, dilation],
    pretrained=is_main_process(), norm_layer=FrozenBatchNorm2d)
```

If you encounter issues locating other files, don't hesitate to reach out, and I am happy to assist you.

**Comment by ChelsieLei** [comment]
Thanks for your reply!

Also, there are other places that use the folder.
i.e., https://github.com/JacobYuan7/RLIPv2/blob/main/models/ParSetransformer.py#L94
and https://github.com/JacobYuan7/RLIPv2/blob/main/models/ParSetransformer.py#L95

Thank you again!

**Comment by JacobYuan7** [comment]
> Thanks for your reply!
> 
> Also, there are other places that use the folder. i.e., https://github.com/JacobYuan7/RLIPv2/blob/main/models/ParSetransformer.py#L94 and https://github.com/JacobYuan7/RLIPv2/blob/main/models/ParSetransformer.py#L95 https://github.com/JacobYuan7/RLIPv2/blob/main/models/DDETR_backbone.py#L127
> 
> Thank you again!

@ChelsieLei 
Hi, with respect to the first two, I changed the local cache file folder. Thus, you can delete them to enable loading from the default cache folder, like:
```python
self.tokenizer = RobertaTokenizerFast.from_pretrained(text_encoder_type)
self.text_encoder = RobertaModel.from_pretrained(text_encoder_type)
```
For the third one, I did not use this pre-training in my final implementation. Thus, I assume code will still work if you ignore it.

**Comment by ChelsieLei** [comment]
Thank you very much! It works now.
