### ISSUE TITLE
How to do inference on custom imgs on vcoco full finetune?

### ISSUE THREAD

**Issue by aixiaodewugege** [JacobYuan7/RLIPv2#4]
I notice that there is a python file for hico but missing for vcoco. Should I change it myself?

**Comment by JacobYuan7** [comment]
@aixiaodewugege 
Hi, thanks for your consistent interest.
Actually, this file is implemented in RLIPv1. Thus, it does not support RLIPv2 currently. But I think you can make simple modifications to support RLIPv2 and VCOCO.

**Comment by Varun-GP** [comment]
Hi, Thank you for such an interesting project. I wanted to try on custom images with one of the best models, but I was not successful in running `inference_on_custom_imgs_hico.py`. 
I also tried previous RLIPv1, however not able to load the correct model. It would be really helpful if a demo/inference script be provided with comments to load the correct model.  Thank you.
