### ISSUE TITLE
Question about relation pesudo-labeling OpenImages dataset

### ISSUE THREAD

**Issue by WonwoongCho** [JacobYuan7/RLIPv2#6]
Hi, thank you for sharing your project.
I saw the pseudo-labeling code for MSCOCO, and I was wondering if you have the one for OpenImages dataset as well.
I would appreciate it if you could share it (if you have)!

**Comment by JacobYuan7** [comment]
@WonwoongCho 
Sorry about this late reply. I think it is in https://github.com/JacobYuan7/BLIP_for_RLIPv2.  (o365)

**Comment by JacobYuan7** [comment]
Feel free to re-open it. I am now closing it as completed.
