### ISSUE TITLE
Links to the checkpoints expired

### ISSUE THREAD

**Issue by maluwastaken** [JacobYuan7/RLIPv2#8]
Hi! When I try to access the checkpoints in the README, sharepoint shows a message saying the link is expired. Could you update them maybe? Thanks!

**Comment by JacobYuan7** [comment]
@maluwastaken 
Thanks for the reminder. I've updated everything.

**Comment by xiexie123** [comment]
it seems like links to the checkpoints expired again. could you please check for me?
